# Generated by Django 5.2.1 on 2026-04-21 18:31

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_church_platform_access_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("agent_name", models.CharField(db_index=True, max_length=255)),
                ("alert_type", models.CharField(db_index=True, max_length=128)),
                ("message", models.TextField()),
                (
                    "severity",
                    models.CharField(db_index=True, default="WARNING", max_length=32),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "church",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_alerts",
                        to="accounts.church",
                    ),
                ),
            ],
            options={
                "db_table": "agent_alerts",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="AgentLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("agent_name", models.CharField(db_index=True, max_length=255)),
                ("action", models.CharField(max_length=255)),
                ("status", models.CharField(db_index=True, max_length=64)),
                ("input_data", models.JSONField(blank=True, default=dict)),
                ("output_data", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True)),
                ("triggered_by", models.CharField(default="SCHEDULED", max_length=64)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "church",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_logs",
                        to="accounts.church",
                    ),
                ),
            ],
            options={
                "db_table": "agent_logs",
                "ordering": ("-created_at",),
            },
        ),
    ]
