"""
Full permission catalog — one row per capability, grouped by Permission.MODULE_CHOICES.

Used by `setup_initial_data` (get_or_create by `code`). Safe to extend; keep `code` stable.
"""

PERMISSIONS_SEED_DATA: list[dict] = [
    {
        "code": "members.view_all",
        "module": "MEMBERS",
        "description": "View all members",
        "is_system_permission": True,
    },
    {
        "code": "members.view_own",
        "module": "MEMBERS",
        "description": "View own household / limited member profile",
        "is_system_permission": True,
    },
    {
        "code": "members.create",
        "module": "MEMBERS",
        "description": "Create new members",
        "is_system_permission": True,
    },
    {
        "code": "members.edit",
        "module": "MEMBERS",
        "description": "Edit member details",
        "is_system_permission": True,
    },
    {
        "code": "members.delete",
        "module": "MEMBERS",
        "description": "Delete or archive members",
        "is_system_permission": True,
    },
    {
        "code": "members.view_financial",
        "module": "MEMBERS",
        "description": "View member financial / giving data",
        "is_system_permission": True,
    },
    {
        "code": "members.export",
        "module": "MEMBERS",
        "description": "Export member lists and reports",
        "is_system_permission": True,
    },
    {
        "code": "members.manage_visitors",
        "module": "MEMBERS",
        "description": "Manage visitor records and conversion",
        "is_system_permission": True,
    },
    {
        "code": "treasury.view",
        "module": "TREASURY",
        "description": "View financial data and dashboards",
        "is_system_permission": True,
    },
    {
        "code": "treasury.record_income",
        "module": "TREASURY",
        "description": "Record income and tithes",
        "is_system_permission": True,
    },
    {
        "code": "treasury.record_expense",
        "module": "TREASURY",
        "description": "Record expenses",
        "is_system_permission": True,
    },
    {
        "code": "treasury.approve_expense",
        "module": "TREASURY",
        "description": "Approve expense requests",
        "is_system_permission": True,
    },
    {
        "code": "treasury.generate_reports",
        "module": "TREASURY",
        "description": "Generate financial reports",
        "is_system_permission": True,
    },
    {
        "code": "treasury.manage_budgets",
        "module": "TREASURY",
        "description": "Create and adjust budgets",
        "is_system_permission": True,
    },
    {
        "code": "treasury.manage_categories",
        "module": "TREASURY",
        "description": "Manage income/expense categories",
        "is_system_permission": True,
    },
    {
        "code": "treasury.reconcile",
        "module": "TREASURY",
        "description": "Perform reconciliation workflows",
        "is_system_permission": True,
    },
    {
        "code": "secretariat.view",
        "module": "SECRETARIAT",
        "description": "View secretariat module and documents",
        "is_system_permission": True,
    },
    {
        "code": "secretariat.create_announcement",
        "module": "SECRETARIAT",
        "description": "Create announcements and notices",
        "is_system_permission": True,
    },
    {
        "code": "secretariat.approve_announcement",
        "module": "SECRETARIAT",
        "description": "Approve announcements for publication",
        "is_system_permission": True,
    },
    {
        "code": "secretariat.send_sms",
        "module": "SECRETARIAT",
        "description": "Send SMS notifications",
        "is_system_permission": True,
    },
    {
        "code": "secretariat.manage_documents",
        "module": "SECRETARIAT",
        "description": "Upload and manage official documents",
        "is_system_permission": True,
    },
    {
        "code": "secretariat.manage_calendar",
        "module": "SECRETARIAT",
        "description": "Manage church calendar entries",
        "is_system_permission": True,
    },
    {
        "code": "departments.view",
        "module": "DEPARTMENTS",
        "description": "View departments and rosters",
        "is_system_permission": True,
    },
    {
        "code": "departments.manage",
        "module": "DEPARTMENTS",
        "description": "Create, edit, and deactivate departments",
        "is_system_permission": True,
    },
    {
        "code": "departments.request_funds",
        "module": "DEPARTMENTS",
        "description": "Request department funds and programs",
        "is_system_permission": True,
    },
    {
        "code": "departments.assign_head",
        "module": "DEPARTMENTS",
        "description": "Assign or change official department head",
        "is_system_permission": True,
    },
    {
        "code": "departments.assign_elder_in_charge",
        "module": "DEPARTMENTS",
        "description": "Assign or change elder in charge for a department",
        "is_system_permission": True,
    },
    {
        "code": "departments.manage_members",
        "module": "DEPARTMENTS",
        "description": "Add or remove members in assigned departments",
        "is_system_permission": True,
    },
    {
        "code": "departments.manage_programs",
        "module": "DEPARTMENTS",
        "description": "Create and manage department programs and activities",
        "is_system_permission": True,
    },
    {
        "code": "departments.approve_programs",
        "module": "DEPARTMENTS",
        "description": "Approve department programs (workflow)",
        "is_system_permission": True,
    },
    {
        "code": "announcements.view",
        "module": "ANNOUNCEMENTS",
        "description": "View published announcements",
        "is_system_permission": True,
    },
    {
        "code": "announcements.create",
        "module": "ANNOUNCEMENTS",
        "description": "Create announcement drafts",
        "is_system_permission": True,
    },
    {
        "code": "announcements.edit",
        "module": "ANNOUNCEMENTS",
        "description": "Edit announcements",
        "is_system_permission": True,
    },
    {
        "code": "announcements.delete",
        "module": "ANNOUNCEMENTS",
        "description": "Delete or unpublish announcements",
        "is_system_permission": True,
    },
    {
        "code": "announcements.publish",
        "module": "ANNOUNCEMENTS",
        "description": "Publish announcements to the congregation",
        "is_system_permission": True,
    },
    {
        "code": "announcements.moderate",
        "module": "ANNOUNCEMENTS",
        "description": "Moderate comments or flagged content",
        "is_system_permission": True,
    },
    {
        "code": "reports.view",
        "module": "REPORTS",
        "description": "View standard reports",
        "is_system_permission": True,
    },
    {
        "code": "reports.create",
        "module": "REPORTS",
        "description": "Build ad-hoc or saved reports",
        "is_system_permission": True,
    },
    {
        "code": "reports.export",
        "module": "REPORTS",
        "description": "Export reports (CSV, PDF, Excel)",
        "is_system_permission": True,
    },
    {
        "code": "reports.schedule",
        "module": "REPORTS",
        "description": "Schedule automated report delivery",
        "is_system_permission": True,
    },
    {
        "code": "reports.manage_templates",
        "module": "REPORTS",
        "description": "Manage organization report templates",
        "is_system_permission": True,
    },
    {
        "code": "reports.sensitive",
        "module": "REPORTS",
        "description": "Access sensitive or leadership-only reports",
        "is_system_permission": True,
    },
    {
        "code": "settings.view",
        "module": "SETTINGS",
        "description": "View church and account settings",
        "is_system_permission": True,
    },
    {
        "code": "settings.edit_church_profile",
        "module": "SETTINGS",
        "description": "Edit church profile, branding, and service times",
        "is_system_permission": True,
    },
    {
        "code": "settings.edit_billing",
        "module": "SETTINGS",
        "description": "Manage subscription and billing",
        "is_system_permission": True,
    },
    {
        "code": "settings.manage_users",
        "module": "SETTINGS",
        "description": "Invite and manage staff users",
        "is_system_permission": True,
    },
    {
        "code": "settings.manage_roles",
        "module": "SETTINGS",
        "description": "Assign roles and permissions (where UI allows)",
        "is_system_permission": True,
    },
    {
        "code": "settings.security",
        "module": "SETTINGS",
        "description": "Manage security settings and sessions",
        "is_system_permission": True,
    },
    {
        "code": "settings.integrations",
        "module": "SETTINGS",
        "description": "Configure third-party integrations",
        "is_system_permission": True,
    },
    {
        "code": "attendance.view",
        "module": "ATTENDANCE",
        "description": "View attendance records and summaries",
        "is_system_permission": True,
    },
    {
        "code": "attendance.record",
        "module": "ATTENDANCE",
        "description": "Record attendance for services or events",
        "is_system_permission": True,
    },
    {
        "code": "attendance.edit",
        "module": "ATTENDANCE",
        "description": "Correct attendance entries",
        "is_system_permission": True,
    },
    {
        "code": "attendance.reports",
        "module": "ATTENDANCE",
        "description": "Run attendance analytics and exports",
        "is_system_permission": True,
    },
    {
        "code": "attendance.manage_sessions",
        "module": "ATTENDANCE",
        "description": "Configure services, gates, or check-in sessions",
        "is_system_permission": True,
    },
    {
        "code": "events.view",
        "module": "EVENTS",
        "description": "View church events",
        "is_system_permission": True,
    },
    {
        "code": "events.create",
        "module": "EVENTS",
        "description": "Create events",
        "is_system_permission": True,
    },
    {
        "code": "events.edit",
        "module": "EVENTS",
        "description": "Edit events",
        "is_system_permission": True,
    },
    {
        "code": "events.delete",
        "module": "EVENTS",
        "description": "Cancel or delete events",
        "is_system_permission": True,
    },
    {
        "code": "events.manage_registrations",
        "module": "EVENTS",
        "description": "Manage RSVPs and registrations",
        "is_system_permission": True,
    },
    {
        "code": "events.manage_volunteers",
        "module": "EVENTS",
        "description": "Assign volunteers and roles for events",
        "is_system_permission": True,
    },
    {
        "code": "communications.view",
        "module": "COMMUNICATIONS",
        "description": "View communication history and campaigns",
        "is_system_permission": True,
    },
    {
        "code": "communications.send_email",
        "module": "COMMUNICATIONS",
        "description": "Send bulk or targeted email",
        "is_system_permission": True,
    },
    {
        "code": "communications.send_sms",
        "module": "COMMUNICATIONS",
        "description": "Send bulk or targeted SMS",
        "is_system_permission": True,
    },
    {
        "code": "communications.manage_templates",
        "module": "COMMUNICATIONS",
        "description": "Create and edit message templates",
        "is_system_permission": True,
    },
    {
        "code": "communications.manage_segments",
        "module": "COMMUNICATIONS",
        "description": "Manage audience segments and lists",
        "is_system_permission": True,
    },
    {
        "code": "communications.view_logs",
        "module": "COMMUNICATIONS",
        "description": "View delivery logs and failures",
        "is_system_permission": True,
    },
]
