# Generated by Django 5.2.1 on 2026-03-23 10:51

import uuid

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Church",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=150, unique=True)),
                (
                    "subdomain",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Subdomain must be 3-63 characters, lowercase letters, numbers, and hyphens only.",
                                regex="^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]$",
                            )
                        ],
                    ),
                ),
                (
                    "denomination",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("country", models.CharField(max_length=100)),
                ("region", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("address", models.TextField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("tagline", models.CharField(blank=True, max_length=500, null=True)),
                ("mission", models.TextField(blank=True, null=True)),
                (
                    "primary_color",
                    models.CharField(blank=True, default="#0B2A4A", max_length=20),
                ),
                (
                    "accent_color",
                    models.CharField(blank=True, default="#2FC4B2", max_length=20),
                ),
                (
                    "sidebar_color",
                    models.CharField(blank=True, default="#0B2A4A", max_length=20),
                ),
                (
                    "background_color",
                    models.CharField(blank=True, default="#F8FAFC", max_length=20),
                ),
                ("dark_mode", models.BooleanField(default=False)),
                ("service_times", models.JSONField(blank=True, default=list)),
                (
                    "church_size",
                    models.CharField(
                        choices=[
                            ("SMALL", "Small (1-100 members)"),
                            ("MEDIUM", "Medium (101-500 members)"),
                            ("LARGE", "Large (500+ members)"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="church_logos/"),
                ),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("currency", models.CharField(default="GHS", max_length=3)),
                ("max_users", models.PositiveIntegerField(default=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("TRIAL", "Trial"),
                            ("INACTIVE", "Inactive"),
                        ],
                        default="TRIAL",
                        max_length=20,
                    ),
                ),
                (
                    "subscription_plan",
                    models.CharField(
                        choices=[
                            ("TRIAL", "Free Trial (30 Days)"),
                            ("FREE", "Free Forever (1 Admin)"),
                            ("BASIC", "Basic - 29 GHS/month (5 Admins)"),
                            ("PREMIUM", "Premium - 79 GHS/month (Unlimited)"),
                            ("ENTERPRISE", "Enterprise"),
                        ],
                        default="TRIAL",
                        max_length=20,
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        blank=True,
                        choices=[("MONTHLY", "Monthly"), ("YEARLY", "Yearly")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                ("subscription_starts_at", models.DateTimeField(blank=True, null=True)),
                ("subscription_ends_at", models.DateTimeField(blank=True, null=True)),
                ("next_billing_date", models.DateTimeField(blank=True, null=True)),
                (
                    "paystack_customer_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "paystack_subscription_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "last_payment_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_payment_date", models.DateTimeField(blank=True, null=True)),
                ("enable_online_giving", models.BooleanField(default=False)),
                ("enable_sms_notifications", models.BooleanField(default=False)),
                ("enable_email_notifications", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Church",
                "verbose_name_plural": "Churches",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "module",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MEMBERS", "Members"),
                            ("TREASURY", "Treasury"),
                            ("SECRETARIAT", "Secretariat"),
                            ("DEPARTMENTS", "Departments"),
                            ("ANNOUNCEMENTS", "Announcements"),
                            ("REPORTS", "Reports"),
                            ("SETTINGS", "Settings"),
                            ("ATTENDANCE", "Attendance"),
                            ("EVENTS", "Events"),
                            ("COMMUNICATIONS", "Communications"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "is_system_permission",
                    models.BooleanField(
                        default=False, help_text="System permissions cannot be deleted"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["module", "code"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (1, "Super Admin (Pastor/First Elder)"),
                            (2, "Core Admin (Secretary/Treasurer)"),
                            (3, "Department Head"),
                            (4, "Member"),
                            (5, "Visitor"),
                        ]
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "is_system_role",
                    models.BooleanField(
                        default=False,
                        help_text="System roles cannot be deleted or modified",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["level", "name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="email address",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="users/profiles"
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("mfa_enabled", models.BooleanField(default=False)),
                ("mfa_secret", models.CharField(blank=True, max_length=32, null=True)),
                ("is_platform_admin", models.BooleanField(default=False)),
                ("failed_login_attempts", models.IntegerField(default=0)),
                ("account_locked_until", models.DateTimeField(blank=True, null=True)),
                (
                    "notification_preference",
                    models.CharField(
                        choices=[
                            ("email", "Email Only"),
                            ("sms", "SMS Only"),
                            ("both", "Both Email and SMS"),
                            ("none", "No Notifications"),
                        ],
                        default="email",
                        help_text="Preferred method for receiving notifications",
                        max_length=10,
                    ),
                ),
                ("email_verified", models.BooleanField(default=False)),
                (
                    "email_verification_token",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "password_reset_token",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("password_reset_expires", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "church",
                    models.ForeignKey(
                        blank=True,
                        db_column="church_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="accounts.church",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ChurchGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "church",
                    models.ForeignKey(
                        db_column="church_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="church_groups",
                        to="accounts.church",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        db_column="role_id",
                        help_text="Role automatically assigned to users in this group",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="church_groups",
                        to="accounts.role",
                    ),
                ),
            ],
            options={
                "db_table": "church_groups",
                "ordering": ["name"],
                "unique_together": {("church", "name")},
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="GHS", max_length=3)),
                ("reference", models.CharField(max_length=100, unique=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("PAYSTACK", "Paystack"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("CARD", "Credit/Debit Card"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESSFUL", "Successful"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("subscription_plan", models.CharField(max_length=50)),
                ("billing_cycle", models.CharField(max_length=20)),
                (
                    "payment_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("next_billing_date", models.DateTimeField(blank=True, null=True)),
                ("payment_details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="accounts.church",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="RegistrationSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("step", models.PositiveSmallIntegerField(default=1)),
                ("data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "db_table": "registration_sessions",
                "indexes": [
                    models.Index(
                        fields=["expires_at"], name="registratio_expires_71725a_idx"
                    ),
                    models.Index(fields=["step"], name="registratio_step_79c1b4_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("VIEW", "View"),
                            ("LOGIN", "Login"),
                            ("LOGIN_FAILED", "Login Failed"),
                            ("LOGOUT", "Logout"),
                            ("PASSWORD_CHANGE", "Password Changed"),
                            ("PASSWORD_RESET", "Password Reset"),
                            ("PERMISSION_CHANGE", "Permission Changed"),
                            ("ROLE_CHANGE", "Role Changed"),
                            ("STATUS_CHANGE", "Status Changed"),
                            ("SYSTEM", "System Event"),
                            ("IMPORT", "Data Import"),
                            ("EXPORT", "Data Export"),
                            ("BACKUP", "Backup Created"),
                            ("RESTORE", "Data Restored"),
                        ],
                        help_text="Type of action performed",
                        max_length=50,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="Name of the affected model", max_length=100
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        help_text="ID of the affected object", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the action"),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        help_text="JSON field storing changed fields and their values",
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of the user who performed the action",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="User agent string from the request",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata about the action",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When the action was performed",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Content type of the affected model",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "church",
                    models.ForeignKey(
                        blank=True,
                        help_text="Church/tenant where the action was performed",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="accounts.church",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="accounts_au_created_721afe_idx"
                    ),
                    models.Index(
                        fields=["action"], name="accounts_au_action_5ca9a9_idx"
                    ),
                    models.Index(
                        fields=["model_name"], name="accounts_au_model_n_5922b8_idx"
                    ),
                    models.Index(
                        fields=["user"], name="accounts_au_user_id_2e9d8e_idx"
                    ),
                    models.Index(
                        fields=["church"], name="accounts_au_church__da633a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ChurchGroupMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="added_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="added_group_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        db_column="church_group_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="accounts.churchgroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="church_group_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "church_group_members",
                "ordering": ["-added_at"],
                "unique_together": {("group", "user")},
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "permission",
                    models.ForeignKey(
                        db_column="permission_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.permission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        db_column="role_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="accounts.role",
                    ),
                ),
            ],
            options={
                "ordering": ["role__name", "permission__code"],
                "unique_together": {("role", "permission")},
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "church",
                    models.ForeignKey(
                        db_column="church_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.church",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        db_column="role_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-assigned_at"],
                "unique_together": {("user", "role", "church")},
            },
        ),
    ]
