# Generated by Django 5.2.10 on 2026-01-09 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_email_per_church",
        ),
        migrations.AddField(
            model_name="user",
            name="is_platform_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="church",
            field=models.ForeignKey(
                blank=True,
                db_column="church_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="accounts.church",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_platform_admin"], name="users_is_plat_1e6c85_idx"
            ),
        ),
    ]
