# Generated by Django 5.2.10 on 2026-01-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_user_unique_email_per_church_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("church__isnull", False)),
                fields=("email", "church"),
                name="unique_email_per_church",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_platform_admin", True)),
                fields=("email",),
                name="unique_email_platform_admin",
            ),
        ),
    ]
