# Generated by Django 5.2.11 on 2026-02-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="church",
            name="subscription_plan",
            field=models.CharField(
                choices=[
                    ("FREE", "Free Forever (1 Admin)"),
                    ("BASIC", "Basic - 29 GHS/month (5 Admins)"),
                    ("PREMIUM", "Premium - 79 GHS/month (Unlimited)"),
                ],
                default="TRIAL",
                max_length=20,
            ),
        ),
    ]
