# Generated by Django 5.2.10 on 2026-01-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_unique_email_per_church_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="church",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="churches/logo"),
        ),
    ]
