# Generated by Django 5.2.11 on 2026-02-15 17:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_church_subscription_plan"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
            },
        ),
        migrations.AddField(
            model_name="auditlog",
            name="changes",
            field=models.JSONField(
                blank=True,
                help_text="JSON field storing changed fields and their values",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Content type of the affected model",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional metadata about the action",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create"),
                    ("UPDATE", "Update"),
                    ("DELETE", "Delete"),
                    ("VIEW", "View"),
                    ("LOGIN", "Login"),
                    ("LOGIN_FAILED", "Login Failed"),
                    ("LOGOUT", "Logout"),
                    ("PASSWORD_CHANGE", "Password Changed"),
                    ("PASSWORD_RESET", "Password Reset"),
                    ("PERMISSION_CHANGE", "Permission Changed"),
                    ("ROLE_CHANGE", "Role Changed"),
                    ("STATUS_CHANGE", "Status Changed"),
                    ("SYSTEM", "System Event"),
                    ("IMPORT", "Data Import"),
                    ("EXPORT", "Data Export"),
                    ("BACKUP", "Backup Created"),
                    ("RESTORE", "Data Restored"),
                ],
                help_text="Type of action performed",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="church",
            field=models.ForeignKey(
                blank=True,
                help_text="Church/tenant where the action was performed",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="accounts.church",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="created_at",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                editable=False,
                help_text="When the action was performed",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="description",
            field=models.TextField(help_text="Detailed description of the action"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="IP address of the user who performed the action",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="model_name",
            field=models.CharField(
                help_text="Name of the affected model", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="object_id",
            field=models.CharField(
                help_text="ID of the affected object", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who performed the action",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="user_agent",
            field=models.TextField(
                blank=True, help_text="User agent string from the request", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["-created_at"], name="accounts_au_created_721afe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["action"], name="accounts_au_action_5ca9a9_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["model_name"], name="accounts_au_model_n_5922b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["user"], name="accounts_au_user_id_2e9d8e_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["church"], name="accounts_au_church__da633a_idx"
            ),
        ),
    ]
