# Generated by Django 5.2.11 on 2026-02-18 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_add_notification_preference"),
        ("accounts", "0004_alter_auditlog_options_auditlog_changes_and_more"),
    ]

    operations = []
