# Generated by Django 5.2.11 on 2026-02-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_merge_20260218_1141"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="user",
                    name="notification_preference",
                    field=models.CharField(
                        choices=[
                            ("email", "Email Only"),
                            ("sms", "SMS Only"),
                            ("both", "Both Email and SMS"),
                            ("none", "No Notifications"),
                        ],
                        default="email",
                        max_length=10,
                        help_text="Preferred method for receiving notifications",
                    ),
                ),
            ],
            database_operations=[],
        )
    ]
