# Generated by Django 5.2.1 on 2026-05-10 23:40

from django.db import migrations, models

import accounts.models.base_models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_platform_directory_plan_resources"),
    ]

    operations = [
        migrations.AlterField(
            model_name="church",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=accounts.models.base_models.church_logo_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=accounts.models.base_models.user_profile_upload_path,
            ),
        ),
    ]
