# Generated by Django 5.2.11 on 2026-02-19 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_add_notification_preference"),
        ("accounts", "0006_notification_preference_fix"),
    ]

    operations = []
