# Generated by Django 5.2.11 on 2026-02-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_merge_20260219_0323"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="notification_preference",
            field=models.CharField(
                choices=[
                    ("email", "Email Only"),
                    ("sms", "SMS Only"),
                    ("both", "Both Email and SMS"),
                    ("none", "No Notifications"),
                ],
                default="email",
                help_text="Preferred method for receiving notifications",
                max_length=10,
            ),
        ),
    ]
