# Generated by Django 5.2.11 on 2026-02-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_user_notification_preference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="church",
            name="subscription_plan",
            field=models.CharField(
                choices=[
                    ("TRIAL", "Free Trial (30 Days)"),
                    ("FREE", "Free Forever (1 Admin)"),
                    ("BASIC", "Basic - 29 GHS/month (5 Admins)"),
                    ("PREMIUM", "Premium - 79 GHS/month (Unlimited)"),
                    ("ENTERPRISE", "Enterprise"),
                ],
                default="TRIAL",
                max_length=20,
            ),
        ),
    ]
