# Generated by Django 5.2.11 on 2026-03-01 07:38

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_church_subscription_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChurchGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "church",
                    models.ForeignKey(
                        db_column="church_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="church_groups",
                        to="accounts.church",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        db_column="role_id",
                        help_text="Role automatically assigned to users in this group",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="church_groups",
                        to="accounts.role",
                    ),
                ),
            ],
            options={
                "db_table": "church_groups",
                "ordering": ["name"],
                "unique_together": {("church", "name")},
            },
        ),
        migrations.CreateModel(
            name="ChurchGroupMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="added_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="added_group_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        db_column="church_group_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="accounts.churchgroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="church_group_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "church_group_members",
                "ordering": ["-added_at"],
                "unique_together": {("group", "user")},
            },
        ),
    ]
