# Generated by Django 5.2.11 on 2026-02-26 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="reportcache",
            new_name="report_cach_church__24af1e_idx",
            old_name="report_cach_church_idx",
        ),
        migrations.RenameIndex(
            model_name="reportcache",
            new_name="report_cach_expires_a7835d_idx",
            old_name="report_cach_expires_idx",
        ),
        migrations.RenameIndex(
            model_name="scheduledreport",
            new_name="scheduled_r_church__5d0019_idx",
            old_name="sched_rep_church_active_idx",
        ),
        migrations.RenameIndex(
            model_name="scheduledreport",
            new_name="scheduled_r_next_ru_d85d4d_idx",
            old_name="sched_rep_next_run_idx",
        ),
    ]
