# Generated by Django 5.2.11 on 2026-02-13 12:10

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("departments", "0001_initial"),
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "church",
                    models.ForeignKey(
                        db_column="church_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_categories",
                        to="accounts.church",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense Category",
                "verbose_name_plural": "Expense Categories",
                "db_table": "expense_categories",
                "ordering": ["name"],
                "unique_together": {("church", "code")},
            },
        ),
        migrations.CreateModel(
            name="ExpenseRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("request_number", models.CharField(max_length=50, unique=True)),
                (
                    "amount_requested",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "amount_approved",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("purpose", models.TextField()),
                ("justification", models.TextField()),
                ("required_by_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("DEPT_HEAD_APPROVED", "Department Head Approved"),
                            ("TREASURER_APPROVED", "Treasurer Approved"),
                            ("FIRST_ELDER_APPROVED", "First Elder Approved"),
                            ("APPROVED", "Fully Approved"),
                            ("REJECTED", "Rejected"),
                            ("DISBURSED", "Disbursed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(blank=True, null=True)),
                ("dept_head_approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "first_elder_approved_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("treasurer_approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("approval_comments", models.TextField(blank=True, null=True)),
                ("disbursed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "disbursed_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expense_requests",
                        to="treasury.expensecategory",
                    ),
                ),
                (
                    "church",
                    models.ForeignKey(
                        db_column="church_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_requests",
                        to="accounts.church",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expense_requests",
                        to="departments.department",
                    ),
                ),
                (
                    "dept_head_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dept_head_expense_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "first_elder_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="first_elder_expense_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_expense_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "treasurer_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="treasurer_expense_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense Request",
                "verbose_name_plural": "Expense Requests",
                "db_table": "expense_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("voucher_number", models.CharField(max_length=50, unique=True)),
                ("transaction_date", models.DateField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("amount_in_words", models.CharField(blank=True, max_length=500)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("CHEQUE", "Cheque"),
                            ("MOBILE_MONEY", "Mobile Money"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("CARD", "Card Payment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cheque_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "transaction_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("bank_name", models.CharField(blank=True, max_length=150, null=True)),
                ("paid_to", models.CharField(max_length=200)),
                (
                    "recipient_phone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "recipient_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("description", models.TextField()),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="treasury.expensecategory",
                    ),
                ),
                (
                    "church",
                    models.ForeignKey(
                        db_column="church_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_transactions",
                        to="accounts.church",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="departments.department",
                    ),
                ),
                (
                    "expense_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="treasury.expenserequest",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense Transaction",
                "verbose_name_plural": "Expense Transactions",
                "db_table": "expense_transactions",
                "ordering": ["-transaction_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IncomeCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "church",
                    models.ForeignKey(
                        db_column="church_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="income_categories",
                        to="accounts.church",
                    ),
                ),
            ],
            options={
                "verbose_name": "Income Category",
                "verbose_name_plural": "Income Categories",
                "db_table": "income_categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="IncomeTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("receipt_number", models.CharField(max_length=50, unique=True)),
                ("transaction_date", models.DateField()),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("SABBATH_SERVICE", "Sabbath Service"),
                            ("MID_WEEK", "Mid-week Service"),
                            ("SPECIAL_EVENT", "Special Event"),
                            ("WALK_IN", "Walk-in Contribution"),
                            ("ONLINE", "Online Contribution"),
                        ],
                        default="SABBATH_SERVICE",
                        max_length=30,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("amount_in_words", models.CharField(blank=True, max_length=500)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("CHEQUE", "Cheque"),
                            ("MOBILE_MONEY", "Mobile Money"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("CARD", "Card Payment"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cheque_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "transaction_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("bank_name", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "contributor_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("is_anonymous", models.BooleanField(default=False)),
                (
                    "project_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="treasury.incomecategory",
                    ),
                ),
                (
                    "church",
                    models.ForeignKey(
                        db_column="church_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="income_transactions",
                        to="accounts.church",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="income_allocations",
                        to="departments.department",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="income_contributions",
                        to="members.member",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_income",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "witnessed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="witnessed_income",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Income Transaction",
                "verbose_name_plural": "Income Transactions",
                "db_table": "income_transactions",
                "ordering": ["-transaction_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("asset_tag", models.CharField(max_length=50, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("LAND_BUILDING", "Land & Buildings"),
                            ("FURNITURE", "Furniture & Fixtures"),
                            ("EQUIPMENT", "Equipment"),
                            ("VEHICLE", "Vehicles"),
                            ("IT_EQUIPMENT", "IT Equipment"),
                            ("MUSICAL_INSTRUMENTS", "Musical Instruments"),
                            ("BOOKS", "Books & Library"),
                            ("OTHER", "Other Assets"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("purchase_date", models.DateField()),
                ("purchase_cost", models.DecimalField(decimal_places=2, max_digits=15)),
                ("supplier", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "current_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("EXCELLENT", "Excellent"),
                            ("GOOD", "Good"),
                            ("FAIR", "Fair"),
                            ("POOR", "Poor"),
                            ("DAMAGED", "Damaged"),
                        ],
                        default="GOOD",
                        max_length=20,
                    ),
                ),
                ("warranty_expiry", models.DateField(blank=True, null=True)),
                (
                    "insurance_policy",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "church",
                    models.ForeignKey(
                        db_column="church_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="accounts.church",
                    ),
                ),
                (
                    "custodian",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="custodian_assets",
                        to="members.member",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="departments.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset",
                "verbose_name_plural": "Assets",
                "db_table": "assets",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["church", "category"], name="assets_church__1a3af9_idx"
                    ),
                    models.Index(
                        fields=["asset_tag"], name="assets_asset_t_3d9023_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="expenserequest",
            index=models.Index(
                fields=["church", "status"], name="expense_req_church__ed77ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expenserequest",
            index=models.Index(
                fields=["department", "status"], name="expense_req_departm_4fd507_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expenserequest",
            index=models.Index(
                fields=["request_number"], name="expense_req_request_d790c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expenserequest",
            index=models.Index(
                fields=["required_by_date"], name="expense_req_require_308388_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expensetransaction",
            index=models.Index(
                fields=["church", "transaction_date"],
                name="expense_tra_church__7e8f42_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="expensetransaction",
            index=models.Index(
                fields=["category", "transaction_date"],
                name="expense_tra_categor_def37d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="expensetransaction",
            index=models.Index(
                fields=["department", "transaction_date"],
                name="expense_tra_departm_a551e4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="expensetransaction",
            index=models.Index(
                fields=["voucher_number"], name="expense_tra_voucher_a00e86_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="incomecategory",
            unique_together={("church", "code")},
        ),
        migrations.AddIndex(
            model_name="incometransaction",
            index=models.Index(
                fields=["church", "transaction_date"],
                name="income_tran_church__dfeeca_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="incometransaction",
            index=models.Index(
                fields=["category", "transaction_date"],
                name="income_tran_categor_71759e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="incometransaction",
            index=models.Index(
                fields=["receipt_number"], name="income_tran_receipt_1830bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incometransaction",
            index=models.Index(
                fields=["member"], name="income_tran_member__23e577_idx"
            ),
        ),
    ]
