# Generated by Django 5.2.11 on 2026-02-28 21:18

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def backfill_income_allocations(apps, schema_editor):
    """Create allocations for existing income transactions."""
    IncomeTransaction = apps.get_model("treasury", "IncomeTransaction")
    IncomeAllocation = apps.get_model("treasury", "IncomeAllocation")
    for txn in IncomeTransaction.objects.filter(deleted_at__isnull=True).select_related(
        "category"
    ):
        if not txn.amount or txn.amount <= 0:
            continue
        try:
            code = txn.category.code.upper() if txn.category else ""
        except Exception:
            code = ""
        amount = txn.amount
        if code == "TITHE":
            IncomeAllocation.objects.create(
                transaction=txn,
                destination="CONFERENCE",
                amount=amount,
                percentage=Decimal("100.00"),
            )
        elif code in ("GENERAL_OFFERING", "LOOSE_OFFERING"):
            half = (amount / 2).quantize(Decimal("0.01"))
            IncomeAllocation.objects.create(
                transaction=txn,
                destination="CHURCH",
                amount=half,
                percentage=Decimal("50.00"),
            )
            IncomeAllocation.objects.create(
                transaction=txn,
                destination="CONFERENCE",
                amount=amount - half,
                percentage=Decimal("50.00"),
            )
        else:
            IncomeAllocation.objects.create(
                transaction=txn,
                destination="CHURCH",
                amount=amount,
                percentage=Decimal("100.00"),
            )


def reverse_backfill(apps, schema_editor):
    pass  # no-op, allocations will be dropped with table


class Migration(migrations.Migration):

    dependencies = [
        ("treasury", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncomeAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "destination",
                    models.CharField(
                        choices=[("CHURCH", "Church"), ("CONFERENCE", "Conference")],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage of total (e.g. 50.00, 100.00)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        db_column="income_transaction_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="treasury.incometransaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Income Allocation",
                "verbose_name_plural": "Income Allocations",
                "db_table": "income_allocations",
                "ordering": ["transaction", "destination"],
            },
        ),
        migrations.RunPython(backfill_income_allocations, reverse_backfill),
    ]
