# Generated by Django 5.2.11 on 2026-02-26 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="churchfile",
            new_name="church_file_church__1065ce_idx",
            old_name="church_file_church__idx",
        ),
        migrations.RenameIndex(
            model_name="churchfile",
            new_name="church_file_church__78a77c_idx",
            old_name="church_file_subfolder_idx",
        ),
    ]
