# Generated by Django 5.2.10 on 2026-01-08 17:16

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
                ("color", models.CharField(blank=True, max_length=20, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "church",
                    models.ForeignKey(
                        db_column="church_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="accounts.church",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "db_table": "departments",
            },
        ),
        migrations.CreateModel(
            name="DepartmentHead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "church",
                    models.ForeignKey(
                        db_column="church_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.church",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        db_column="department_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heads",
                        to="departments.department",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        db_column="member_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department Head",
                "verbose_name_plural": "Department Heads",
                "db_table": "department_heads",
            },
        ),
        migrations.CreateModel(
            name="MemberDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_in_department",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "church",
                    models.ForeignKey(
                        db_column="church_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.church",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        db_column="department_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="departments.department",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        db_column="member_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Member Department",
                "verbose_name_plural": "Member Departments",
                "db_table": "member_departments",
            },
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["church", "is_active"], name="departments_church__a6c248_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("church", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="departmenthead",
            unique_together={("department", "member")},
        ),
        migrations.AlterUniqueTogether(
            name="memberdepartment",
            unique_together={("member", "department")},
        ),
    ]
