# Generated by Django 5.2.1 on 2026-03-23 10:51

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
                ("color", models.CharField(blank=True, max_length=20, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "church",
                    models.ForeignKey(
                        db_column="church_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="accounts.church",
                    ),
                ),
                (
                    "elder_in_charge",
                    models.ForeignKey(
                        blank=True,
                        help_text="The elder who oversees this department and approves programs first",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="departments_as_elder",
                        to="members.member",
                        verbose_name="Elder in charge",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "db_table": "departments",
            },
        ),
        migrations.CreateModel(
            name="DepartmentActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPCOMING", "Upcoming"),
                            ("ONGOING", "Ongoing"),
                            ("PAST", "Past"),
                        ],
                        default="UPCOMING",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("expected_attendance", models.IntegerField(blank=True, null=True)),
                ("actual_attendance", models.IntegerField(blank=True, null=True)),
                (
                    "budget_allocated",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "budget_spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "church",
                    models.ForeignKey(
                        db_column="church_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.church",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        db_column="department_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="departments.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department Activity",
                "verbose_name_plural": "Department Activities",
                "db_table": "department_activities",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="DepartmentHead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "church",
                    models.ForeignKey(
                        db_column="church_id",
                        help_text="The church this department head belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.church",
                        verbose_name="Church",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        db_column="department_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heads",
                        to="departments.department",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        db_column="member_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department Head",
                "verbose_name_plural": "Department Heads",
                "db_table": "department_heads",
            },
        ),
        migrations.CreateModel(
            name="MemberDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_in_department",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "church",
                    models.ForeignKey(
                        db_column="church_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.church",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        db_column="department_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="departments.department",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        db_column="member_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Member Department",
                "verbose_name_plural": "Member Departments",
                "db_table": "member_departments",
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted for Review"),
                            ("ELDER_APPROVED", "Approved by Department Elder"),
                            ("SECRETARIAT_APPROVED", "Approved by Secretariat"),
                            ("TREASURY_APPROVED", "Approved by Treasury"),
                            ("APPROVED", "Fully Approved"),
                            ("REJECTED", "Rejected"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "fiscal_year",
                    models.PositiveIntegerField(
                        blank=True, help_text="Budget fiscal year", null=True
                    ),
                ),
                (
                    "budget_title",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("budget_overview", models.TextField(blank=True, null=True)),
                (
                    "submitted_by_department_head",
                    models.BooleanField(
                        default=True,
                        help_text="False if submitter selected a department they are not head of",
                    ),
                ),
                (
                    "department_head_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "department_head_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "department_head_phone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("strategic_objectives", models.TextField(blank=True, null=True)),
                ("expected_impact", models.TextField(blank=True, null=True)),
                ("ministry_benefits", models.TextField(blank=True, null=True)),
                ("previous_year_comparison", models.TextField(blank=True, null=True)),
                (
                    "number_of_beneficiaries",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("implementation_timeline", models.TextField(blank=True, null=True)),
                (
                    "total_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_expenses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "net_budget",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "submission_type",
                    models.CharField(
                        choices=[
                            ("BOTH", "Both Secretariat & Treasury"),
                            ("SECRETARIAT_ONLY", "Secretariat Only"),
                            ("TREASURY_ONLY", "Treasury Only"),
                        ],
                        default="BOTH",
                        help_text="Which departments need to approve this program?",
                        max_length=20,
                    ),
                ),
                ("submitted_to_secretariat", models.BooleanField(default=False)),
                ("submitted_to_treasury", models.BooleanField(default=False)),
                ("secretariat_approved", models.BooleanField(default=False)),
                ("treasury_approved", models.BooleanField(default=False)),
                (
                    "secretariat_approved_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("treasury_approved_at", models.DateTimeField(blank=True, null=True)),
                ("secretariat_notes", models.TextField(blank=True, null=True)),
                ("treasury_notes", models.TextField(blank=True, null=True)),
                ("elder_approved", models.BooleanField(default=False)),
                ("elder_approved_at", models.DateTimeField(blank=True, null=True)),
                ("elder_notes", models.TextField(blank=True, null=True)),
                ("elder_rejected_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.church",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_programs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="departments.department",
                    ),
                ),
                (
                    "elder_rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="elder_rejected_programs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_programs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Program",
                "verbose_name_plural": "Programs",
                "db_table": "programs",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="ProgramBudgetItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[("INCOME", "Income"), ("EXPENSE", "Expense")],
                        default="EXPENSE",
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PERSONNEL_STAFF", "Personnel & Staff"),
                            ("PROGRAM_ACTIVITY", "Program & Activity"),
                            ("EQUIPMENT_SUPPLIES", "Equipment & Supplies"),
                            ("CUSTOM", "Custom"),
                        ],
                        help_text="Budget category for 5-step submission flow",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "income_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CHURCH_COFFERS", "Church Coffers"),
                            ("SILVER_COLLECTION", "Silver Collection"),
                            ("HARVEST", "Harvest"),
                            ("DONATION", "Donation"),
                            ("OUTSOURCE", "Outsource"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("description", models.CharField(max_length=300)),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, help_text="Quantity for expense items"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount in GHS (quantity × unit price)",
                        max_digits=15,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_items",
                        to="departments.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program Budget Item",
                "verbose_name_plural": "Program Budget Items",
                "db_table": "program_budget_items",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProgramDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=500, upload_to="program_documents/%Y/%m/"
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, help_text="File size in bytes"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "program",
                    models.ForeignKey(
                        db_column="program_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="departments.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program Document",
                "verbose_name_plural": "Program Documents",
                "db_table": "program_documents",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["church", "is_active"], name="departments_church__a6c248_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("church", "code")},
        ),
        migrations.AddIndex(
            model_name="departmentactivity",
            index=models.Index(
                fields=["department", "status"], name="department__departm_327b34_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="departmentactivity",
            index=models.Index(
                fields=["church", "deleted_at"], name="department__church__ab3cb8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="departmentactivity",
            index=models.Index(
                fields=["created_at"], name="department__created_3069a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="departmentactivity",
            index=models.Index(
                fields=["start_date"], name="department__start_d_cc363b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="departmenthead",
            unique_together={("department", "member")},
        ),
        migrations.AlterUniqueTogether(
            name="memberdepartment",
            unique_together={("member", "department")},
        ),
    ]
