# Generated by Django 5.2.11 on 2026-02-13 12:10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
                ("color", models.CharField(blank=True, max_length=20, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "church",
                    models.ForeignKey(
                        db_column="church_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="accounts.church",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "db_table": "departments",
            },
        ),
        migrations.CreateModel(
            name="DepartmentActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("ONGOING", "Ongoing"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("expected_attendance", models.IntegerField(blank=True, null=True)),
                ("actual_attendance", models.IntegerField(blank=True, null=True)),
                (
                    "budget_allocated",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "budget_spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "church",
                    models.ForeignKey(
                        db_column="church_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.church",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        db_column="department_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="departments.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department Activity",
                "verbose_name_plural": "Department Activities",
                "db_table": "department_activities",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="DepartmentBudget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("ANNUAL", "Annual"),
                            ("QUARTERLY", "Quarterly"),
                            ("YEARLY", "Yearly"),
                            ("MONTHLY", "Monthly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("year", models.IntegerField()),
                ("quarter", models.IntegerField(blank=True, null=True)),
                ("month", models.IntegerField(blank=True, null=True)),
                (
                    "allocated_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "spent_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        db_column="department_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="departments.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department Budget",
                "verbose_name_plural": "Department Budgets",
                "db_table": "department_budgets",
            },
        ),
        migrations.CreateModel(
            name="DepartmentHead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "church",
                    models.ForeignKey(
                        db_column="church_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.church",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        db_column="department_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heads",
                        to="departments.department",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        db_column="member_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department Head",
                "verbose_name_plural": "Department Heads",
                "db_table": "department_heads",
            },
        ),
        migrations.CreateModel(
            name="MemberDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_in_department",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "church",
                    models.ForeignKey(
                        db_column="church_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.church",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        db_column="department_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="departments.department",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        db_column="member_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Member Department",
                "verbose_name_plural": "Member Departments",
                "db_table": "member_departments",
            },
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["church", "is_active"], name="departments_church__a6c248_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("church", "code")},
        ),
        migrations.AddIndex(
            model_name="departmentactivity",
            index=models.Index(
                fields=["department", "status"], name="department__departm_327b34_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="departmentactivity",
            index=models.Index(
                fields=["church", "deleted_at"], name="department__church__ab3cb8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="departmentactivity",
            index=models.Index(
                fields=["created_at"], name="department__created_3069a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="departmentactivity",
            index=models.Index(
                fields=["start_date"], name="department__start_d_cc363b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="departmentbudget",
            index=models.Index(
                fields=["department", "period", "year", "quarter", "month"],
                name="department__departm_a3be36_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="departmenthead",
            unique_together={("department", "member")},
        ),
        migrations.AlterUniqueTogether(
            name="memberdepartment",
            unique_together={("member", "department")},
        ),
    ]
