# Generated by Django 5.2.11 on 2026-02-19 03:24

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_user_notification_preference"),
        ("departments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted for Review"),
                            ("SECRETARIAT_APPROVED", "Approved by Secretariat"),
                            ("TREASURY_APPROVED", "Approved by Treasury"),
                            ("APPROVED", "Fully Approved"),
                            ("REJECTED", "Rejected"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "total_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_expenses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "net_budget",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "submission_type",
                    models.CharField(
                        choices=[
                            ("BOTH", "Both Secretariat & Treasury"),
                            ("SECRETARIAT_ONLY", "Secretariat Only"),
                            ("TREASURY_ONLY", "Treasury Only"),
                        ],
                        default="BOTH",
                        help_text="Which departments need to approve this program?",
                        max_length=20,
                    ),
                ),
                ("submitted_to_secretariat", models.BooleanField(default=False)),
                ("submitted_to_treasury", models.BooleanField(default=False)),
                ("secretariat_approved", models.BooleanField(default=False)),
                ("treasury_approved", models.BooleanField(default=False)),
                (
                    "secretariat_approved_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("treasury_approved_at", models.DateTimeField(blank=True, null=True)),
                ("secretariat_notes", models.TextField(blank=True, null=True)),
                ("treasury_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.church",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_programs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="departments.department",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_programs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Program",
                "verbose_name_plural": "Programs",
                "db_table": "programs",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="ProgramBudgetItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[("INCOME", "Income"), ("EXPENSE", "Expense")],
                        max_length=10,
                    ),
                ),
                (
                    "income_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CHURCH_COFFERS", "Church Coffers"),
                            ("SILVER_COLLECTION", "Silver Collection"),
                            ("HARVEST", "Harvest"),
                            ("DONATION", "Donation"),
                            ("OUTSOURCE", "Outsource"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_items",
                        to="departments.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program Budget Item",
                "verbose_name_plural": "Program Budget Items",
                "db_table": "program_budget_items",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="DepartmentBudget",
        ),
    ]
