# Generated by Django 5.2.1 on 2026-04-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0002_department_head_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departmenthead",
            name="head_role",
            field=models.CharField(
                choices=[("HEAD", "Department head"), ("ASSISTANT", "Assistant head")],
                db_index=True,
                default="HEAD",
                max_length=20,
            ),
        ),
    ]
