# Generated by Django 5.2.11 on 2026-02-23 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_church_subscription_plan"),
        ("departments", "0002_program_programbudgetitem_delete_departmentbudget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departmenthead",
            name="church",
            field=models.ForeignKey(
                db_column="church_id",
                help_text="The church this department head belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.church",
                verbose_name="Church",
            ),
        ),
    ]
