# Generated by Django 5.2.11 on 2026-02-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0006_program_5step_flow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SUBMITTED", "Submitted for Review"),
                    ("ELDER_APPROVED", "Approved by Department Elder"),
                    ("SECRETARIAT_APPROVED", "Approved by Secretariat"),
                    ("TREASURY_APPROVED", "Approved by Treasury"),
                    ("APPROVED", "Fully Approved"),
                    ("REJECTED", "Rejected"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="programbudgetitem",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Total amount in GHS (quantity × unit price)",
                max_digits=15,
            ),
        ),
    ]
