# Generated by Django 5.2.11 on 2026-02-23 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0007_alter_program_status_alter_programbudgetitem_amount"),
        ("members", "0005_add_baptism_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="elder_in_charge",
            field=models.ForeignKey(
                blank=True,
                help_text="The elder who oversees this department and approves programs first",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="departments_as_elder",
                to="members.member",
                verbose_name="Elder in charge",
            ),
        ),
    ]
