# Generated by Django 5.2.11 on 2026-03-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0008_add_elder_in_charge"),
    ]

    operations = [
        migrations.AddField(
            model_name="departmentactivity",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="departmentactivity",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
