# Generated by Django 5.2.11

from django.db import migrations, models


def convert_activity_status(apps, schema_editor):
    DepartmentActivity = apps.get_model("departments", "DepartmentActivity")
    mapping = {
        "PLANNED": "UPCOMING",
        "ONGOING": "ONGOING",
        "COMPLETED": "PAST",
        "CANCELLED": "PAST",
    }
    for old, new in mapping.items():
        DepartmentActivity.objects.filter(status=old).update(status=new)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0009_add_activity_start_end_time"),
    ]

    operations = [
        migrations.RunPython(convert_activity_status, noop),
        migrations.AlterField(
            model_name="departmentactivity",
            name="status",
            field=models.CharField(
                choices=[
                    ("UPCOMING", "Upcoming"),
                    ("ONGOING", "Ongoing"),
                    ("PAST", "Past"),
                ],
                default="UPCOMING",
                max_length=20,
            ),
        ),
    ]
