# Generated by Django 5.2.11 on 2026-02-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backup", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="backuprecord",
            name="church_id",
            field=models.UUIDField(
                blank=True,
                help_text="For tenant backups: the church that was exported.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="backuprecord",
            name="backup_type",
            field=models.CharField(
                choices=[
                    ("full", "Full database"),
                    ("lightweight", "Lightweight (exclude logs/audit)"),
                    ("tenant", "Tenant (single church export)"),
                ],
                default="full",
                max_length=20,
            ),
        ),
    ]
