# Generated by Django 5.2.1 on 2026-03-23 10:51

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "-- Select Title --"),
                            ("Mr", "Mr"),
                            ("Mrs", "Mrs"),
                            ("Miss", "Miss"),
                            ("Dr", "Dr"),
                            ("Rev", "Rev"),
                            ("Pastor", "Pastor"),
                            ("Elder", "Elder"),
                            ("Deacon", "Deacon"),
                            ("Deaconess", "Deaconess"),
                        ],
                        help_text="Person's title (e.g., Mr, Mrs, Dr, Rev)",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("MALE", "Male"), ("FEMALE", "Female")], max_length=10
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SINGLE", "Single"),
                            ("MARRIED", "Married"),
                            ("WIDOWED", "Widowed"),
                            ("DIVORCED", "Divorced"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("national_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=150, null=True, unique=True
                    ),
                ),
                ("password", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "notification_preference",
                    models.CharField(
                        choices=[
                            ("NONE", "No notifications"),
                            ("EMAIL", "Email only"),
                            ("SMS", "SMS only"),
                            ("BOTH", "Email and SMS"),
                        ],
                        default="EMAIL",
                        help_text="Preferred method for receiving notifications",
                        max_length=5,
                    ),
                ),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "membership_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("TRANSFER", "Transfer"),
                            ("NEW_CONVERT", "New Convert"),
                            ("VISITOR", "Visitor"),
                            ("INACTIVE", "Inactive"),
                        ],
                        default="ACTIVE",
                        max_length=30,
                    ),
                ),
                ("member_since", models.DateField()),
                (
                    "baptism_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BAPTISED", "Baptised"),
                            ("NOT_BAPTISED", "Not Baptised"),
                        ],
                        help_text="Whether the member is baptised or not",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "education_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PRIMARY", "Primary"),
                            ("SECONDARY", "Secondary/High School"),
                            ("TERTIARY", "Tertiary/College"),
                            ("GRADUATE", "Graduate"),
                            ("POSTGRADUATE", "Postgraduate"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("occupation", models.CharField(blank=True, max_length=100, null=True)),
                ("employer", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "emergency_contact_relationship",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("has_system_access", models.BooleanField(default=False)),
                ("system_user_id", models.UUIDField(blank=True, null=True)),
                ("profile_photo", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "church",
                    models.ForeignKey(
                        db_column="church_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="accounts.church",
                    ),
                ),
            ],
            options={
                "verbose_name": "Member",
                "verbose_name_plural": "Members",
                "db_table": "members",
            },
        ),
        migrations.CreateModel(
            name="MemberLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phone_primary", models.CharField(max_length=50)),
                (
                    "phone_secondary",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=150, null=True)),
                ("address", models.TextField()),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "church",
                    models.ForeignKey(
                        db_column="church_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.church",
                    ),
                ),
                (
                    "member",
                    models.OneToOneField(
                        db_column="member_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Member Location",
                "verbose_name_plural": "Member Locations",
                "db_table": "member_locations",
            },
        ),
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("MALE", "Male"), ("FEMALE", "Female")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("phone", models.CharField(max_length=50)),
                ("email", models.EmailField(blank=True, max_length=150, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("first_visit_date", models.DateField()),
                (
                    "referral_source",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("receive_updates", models.BooleanField(default=True)),
                ("converted_to_member", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "church",
                    models.ForeignKey(
                        db_column="church_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitors",
                        to="accounts.church",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visitor",
                "verbose_name_plural": "Visitors",
                "db_table": "visitors",
            },
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(
                fields=["church", "membership_status"],
                name="members_church__0b9521_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(
                fields=["church", "deleted_at"], name="members_church__fe46ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(
                fields=["last_name", "first_name"], name="members_last_na_ac5ab0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visitor",
            index=models.Index(
                fields=["church", "converted_to_member"],
                name="visitors_church__242d77_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="visitor",
            index=models.Index(
                fields=["first_visit_date"], name="visitors_first_v_f9b227_idx"
            ),
        ),
    ]
