# Generated by Django 5.2.11 on 2026-02-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_auto_20240215_0845"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="title",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "-- Select Title --"),
                    ("Mr", "Mr"),
                    ("Mrs", "Mrs"),
                    ("Miss", "Miss"),
                    ("Dr", "Dr"),
                    ("Rev", "Rev"),
                    ("Pastor", "Pastor"),
                    ("Elder", "Elder"),
                    ("Deacon", "Deacon"),
                    ("Deaconess", "Deaconess"),
                ],
                help_text="Person's title (e.g., Mr, Mrs, Dr, Rev)",
                max_length=20,
                null=True,
            ),
        ),
    ]
