# Generated by Django 5.2.11 on 2026-02-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_alter_member_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="member",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="notification_preference",
            field=models.CharField(
                choices=[
                    ("NONE", "No notifications"),
                    ("EMAIL", "Email only"),
                    ("SMS", "SMS only"),
                    ("BOTH", "Email and SMS"),
                ],
                default="EMAIL",
                help_text="Preferred method for receiving notifications",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
