# Generated by Django 5.2.11 on 2026-02-13 12:10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("enable_in_app", models.BooleanField(default=True)),
                ("enable_email", models.BooleanField(default=True)),
                ("enable_sms", models.BooleanField(default=True)),
                ("announcements", models.BooleanField(default=True)),
                ("reminders", models.BooleanField(default=True)),
                ("birthdays", models.BooleanField(default=True)),
                ("events", models.BooleanField(default=True)),
                ("finance", models.BooleanField(default=True)),
                ("digest_mode", models.BooleanField(default=False)),
                (
                    "digest_frequency",
                    models.CharField(
                        blank=True,
                        choices=[("DAILY", "Daily"), ("WEEKLY", "Weekly")],
                        default="DAILY",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("quiet_hours_enabled", models.BooleanField(default=False)),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
                "db_table": "notification_preferences",
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("SMS", "SMS"),
                            ("EMAIL", "Email"),
                            ("IN_APP", "In-App"),
                            ("ALL", "All Channels"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ANNOUNCEMENT", "Announcement"),
                            ("REMINDER", "Reminder"),
                            ("BIRTHDAY", "Birthday"),
                            ("EVENT", "Event"),
                            ("FINANCE", "Finance"),
                            ("GENERAL", "General"),
                        ],
                        max_length=50,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=200, null=True)),
                ("message", models.TextField()),
                ("is_system_template", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "church",
                    models.ForeignKey(
                        blank=True,
                        db_column="church_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_templates",
                        to="accounts.church",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Template",
                "verbose_name_plural": "Notification Templates",
                "db_table": "notification_templates",
            },
        ),
        migrations.CreateModel(
            name="NotificationBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("target_all_members", models.BooleanField(default=False)),
                ("target_departments", models.JSONField(blank=True, null=True)),
                ("target_members", models.JSONField(blank=True, null=True)),
                ("message", models.TextField()),
                ("send_sms", models.BooleanField(default=False)),
                ("send_email", models.BooleanField(default=False)),
                ("send_in_app", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("total_recipients", models.IntegerField(default=0)),
                ("successful_count", models.IntegerField(default=0)),
                ("failed_count", models.IntegerField(default=0)),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "church",
                    models.ForeignKey(
                        db_column="church_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_batches",
                        to="accounts.church",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="notifications.notificationtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Batch",
                "verbose_name_plural": "Notification Batches",
                "db_table": "notification_batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SMSLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Phone Number"
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "message_length",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Message Length"
                    ),
                ),
                (
                    "sms_count",
                    models.PositiveIntegerField(default=1, verbose_name="SMS Count"),
                ),
                (
                    "gateway",
                    models.CharField(
                        choices=[
                            ("MNOTIFY", "mNotify"),
                            ("AFRICASTALKING", "Africa's Talking"),
                            ("TWILIO", "Twilio"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        default="MNOTIFY",
                        max_length=20,
                        verbose_name="Gateway",
                    ),
                ),
                (
                    "gateway_message_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=200,
                        null=True,
                        verbose_name="Gateway Message ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("INBOUND", "Inbound"), ("OUTBOUND", "Outbound")],
                        db_index=True,
                        default="OUTBOUND",
                        max_length=10,
                        verbose_name="Direction",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING", "Pending"),
                            ("QUEUED", "Queued"),
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "delivery_status",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Delivery Status",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Error Message"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="Cost",
                    ),
                ),
                (
                    "price_unit",
                    models.CharField(
                        default="GHS",
                        help_text="Currency code for the cost (e.g., GHS, USD)",
                        max_length=3,
                        verbose_name="Price Unit",
                    ),
                ),
                (
                    "scheduled_for",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Scheduled For",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Sent At"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Delivered At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "church",
                    models.ForeignKey(
                        db_column="church_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_logs",
                        to="accounts.church",
                        verbose_name="Church",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        db_column="member_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="members.member",
                        verbose_name="Member",
                    ),
                ),
            ],
            options={
                "verbose_name": "SMS Log",
                "verbose_name_plural": "SMS Logs",
                "db_table": "sms_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SMSDeliveryReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("undelivered", "Undelivered"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "status_code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Status Code"
                    ),
                ),
                (
                    "status_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Status Message"
                    ),
                ),
                (
                    "delivery_timestamp",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Delivery Timestamp"
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(default=0, verbose_name="Retry Count"),
                ),
                (
                    "last_retry",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Retry"
                    ),
                ),
                (
                    "gateway_response",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Gateway Response"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "sms_log",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_report",
                        to="notifications.smslog",
                        verbose_name="SMS Log",
                    ),
                ),
            ],
            options={
                "verbose_name": "SMS Delivery Report",
                "verbose_name_plural": "SMS Delivery Reports",
                "ordering": ["-delivery_timestamp", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email_address", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("message_html", models.TextField(blank=True, null=True)),
                ("message_plain", models.TextField(blank=True, null=True)),
                ("has_attachments", models.BooleanField(default=False)),
                ("attachment_urls", models.JSONField(blank=True, null=True)),
                ("gateway", models.CharField(default="sendgrid", max_length=50)),
                (
                    "gateway_message_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("QUEUED", "Queued"),
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("OPENED", "Opened"),
                            ("CLICKED", "Clicked"),
                            ("BOUNCED", "Bounced"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("opened_count", models.IntegerField(default=0)),
                ("clicked_count", models.IntegerField(default=0)),
                ("first_opened_at", models.DateTimeField(blank=True, null=True)),
                ("last_opened_at", models.DateTimeField(blank=True, null=True)),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "church",
                    models.ForeignKey(
                        db_column="church_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_logs",
                        to="accounts.church",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        db_column="member_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="members.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Log",
                "verbose_name_plural": "Email Logs",
                "db_table": "email_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["church", "status"],
                        name="email_logs_church__852f0d_idx",
                    ),
                    models.Index(
                        fields=["email_address"], name="email_logs_email_a_3e620e_idx"
                    ),
                    models.Index(
                        fields=["gateway_message_id"],
                        name="email_logs_gateway_c2986a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                ("link", models.URLField(blank=True, null=True)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("READ", "Read"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "church",
                    models.ForeignKey(
                        db_column="church_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="accounts.church",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        db_column="member_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="members.member",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["church", "user", "is_read"],
                        name="notificatio_church__9ba148_idx",
                    ),
                    models.Index(
                        fields=["status", "scheduled_for"],
                        name="notificatio_status_2554f4_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="notificatio_created_e4c995_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="notificationtemplate",
            index=models.Index(
                fields=["church", "category"], name="notificatio_church__b1ec8f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationtemplate",
            index=models.Index(
                fields=["template_type"], name="notificatio_templat_b63ef6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smslog",
            index=models.Index(
                fields=["status", "scheduled_for"], name="sms_logs_status_cec8f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smslog",
            index=models.Index(
                fields=["phone_number", "church"], name="sms_logs_phone_n_f388d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smslog",
            index=models.Index(
                fields=["phone_number"], name="notificatio_phone_n_a773e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smslog",
            index=models.Index(
                fields=["gateway_message_id"], name="notificatio_gateway_d43fee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smsdeliveryreport",
            index=models.Index(fields=["status"], name="notificatio_status_ce5b83_idx"),
        ),
        migrations.AddIndex(
            model_name="smsdeliveryreport",
            index=models.Index(
                fields=["delivery_timestamp"], name="notificatio_deliver_4c69e5_idx"
            ),
        ),
    ]
