# Generated by Django 5.2.11 on 2026-03-11 17:02

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_fix_auditlog_user_fk_on_delete"),
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringNotificationSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("message", models.TextField()),
                ("target_all_members", models.BooleanField(default=False)),
                ("target_departments", models.JSONField(blank=True, null=True)),
                ("target_members", models.JSONField(blank=True, null=True)),
                ("send_sms", models.BooleanField(default=False)),
                ("send_email", models.BooleanField(default=False)),
                ("send_in_app", models.BooleanField(default=False)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("YEARLY", "Yearly"),
                        ],
                        default="WEEKLY",
                        max_length=20,
                    ),
                ),
                (
                    "interval",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Every N days/weeks/months/years (e.g. 2 = every 2 weeks)",
                    ),
                ),
                (
                    "time_of_day",
                    models.TimeField(
                        help_text="Time of day to send (e.g. 12:00 for noon)"
                    ),
                ),
                (
                    "weekdays",
                    models.JSONField(
                        blank=True,
                        help_text="For WEEKLY: list of weekdays 0-6 (0=Mon, 6=Sun). E.g. [2] = Wednesday.",
                        null=True,
                    ),
                ),
                (
                    "month_day",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="For MONTHLY: day of month (1-31).",
                        null=True,
                    ),
                ),
                (
                    "year_month",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="For YEARLY: month (1-12).", null=True
                    ),
                ),
                (
                    "year_month_day",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="For YEARLY: day of month (1-31).",
                        null=True,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(help_text="First run on or after this date."),
                ),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "end_after_occurrences",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Stop after this many sends (optional).",
                        null=True,
                    ),
                ),
                (
                    "next_run_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Next scheduled run (computed and updated after each send).",
                        null=True,
                    ),
                ),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("occurrence_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "church",
                    models.ForeignKey(
                        db_column="church_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_notification_schedules",
                        to="accounts.church",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurring_notification_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurring_schedules",
                        to="notifications.notificationtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurring Notification Schedule",
                "verbose_name_plural": "Recurring Notification Schedules",
                "db_table": "recurring_notification_schedules",
                "ordering": ["next_run_at"],
            },
        ),
    ]
